### ISSUE TITLE
Segfault with handle_redirects function

### ISSUE THREAD

**Issue by vasilisalmpanis** [vasilisalmpanis/Minishell#16]
It is segfaulting when i use it with fsanitize. I fixed the check quotes function so it is not segfaulting anymore it was due to index arithmetics causing an invalid read. Maybe you can take a look at these two because fsanitize shows handle_redirects and calc_redir_wo_space. Also after handling it the tokenization is wrong. If you run ft_show_tab and you pass > or < as an input it tokenizes as word not as redir.

**Comment by memaar92** [comment]
Should be solved with PR #17
